spring:
  application:
    name: user-service
  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
