spring:
  application:
    name: workout-service
  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
