spring:
  application:
    name: llm-service
  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8087

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
